# Generated by Django 3.1.4 on 2020-12-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupiluser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
