# Generated by Django 3.1.4 on 2020-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0002_auto_20201230_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupiluser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
    ]
