# Generated by Django 3.1.4 on 2020-12-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0003_auto_20201230_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupiluser',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pupiluser',
            name='rating',
            field=models.CharField(max_length=100, verbose_name='Успеваемость'),
        ),
    ]
