# Generated by Django 3.1.4 on 2020-12-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0004_auto_20201230_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupiluser',
            name='fav_subj',
            field=models.CharField(max_length=100, verbose_name='Любимый предмет'),
        ),
    ]
