# Generated by Django 3.1.4 on 2020-12-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0005_auto_20201230_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupiluser',
            name='fav_subj',
        ),
        migrations.RemoveField(
            model_name='pupiluser',
            name='n_class',
        ),
        migrations.RemoveField(
            model_name='pupiluser',
            name='rating',
        ),
    ]
