# Generated by Django 3.1.4 on 2021-01-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0006_auto_20201230_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PupilUser',
        ),
    ]
