# Generated by Django 3.1.4 on 2021-01-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='ListHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('homeworks', models.CharField(max_length=255, verbose_name='Дз')),
                ('date', models.DateField(verbose_name='Дата сдачи')),
                ('subj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subjects', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Домашка',
                'verbose_name_plural': 'Домашка',
            },
        ),
    ]
