# Generated by Django 3.1.4 on 2021-01-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number_class', models.PositiveIntegerField(verbose_name='Класс')),
                ('fav_subj', models.CharField(max_length=30, verbose_name='Любимый предмет')),
            ],
        ),
    ]
