# Generated by Django 3.1.4 on 2021-01-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
    ]
