# Generated by Django 3.1.4 on 2021-01-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Типы задания',
                'verbose_name_plural': 'Типы задания',
            },
        ),
        migrations.RemoveField(
            model_name='listhomework',
            name='homeworks',
        ),
        migrations.AddField(
            model_name='listhomework',
            name='homework',
            field=models.TextField(null=True, verbose_name='Дз'),
        ),
        migrations.AlterField(
            model_name='listhomework',
            name='date',
            field=models.TextField(verbose_name='Даты сдачи'),
        ),
        migrations.AddField(
            model_name='listhomework',
            name='matrix_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.matrix', verbose_name='Тип задания'),
        ),
    ]
