# Generated by Django 3.1.4 on 2021-01-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listhomework',
            old_name='homeworks',
            new_name='homework',
        ),
    ]
