# Generated by Django 3.1.4 on 2021-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210103_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='info',
            field=models.BooleanField(default=False, verbose_name='Наличие'),
        ),
    ]
