# Generated by Django 3.1.4 on 2021-01-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210104_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listhomework',
            name='date',
            field=models.TextField(verbose_name='Даты сдачи'),
        ),
        migrations.AlterField(
            model_name='listhomework',
            name='homework',
            field=models.TextField(verbose_name='Дз'),
        ),
    ]
