# Generated by Django 3.1.4 on 2021-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210119_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listhomework',
            name='homework',
            field=models.TextField(verbose_name='Дз'),
        ),
        migrations.AlterField(
            model_name='listhomework',
            name='matrix_type',
            field=models.TextField(verbose_name='Тип задания'),
        ),
    ]
