# Generated by Django 3.1.4 on 2021-01-03 12:40

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_info_info'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='info',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
