# Generated by Django 3.1.4 on 2021-01-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210103_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
