# Generated by Django 3.1.4 on 2021-01-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210119_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='listhomework',
            name='notes',
            field=models.TextField(default='Нет', verbose_name='Записи'),
        ),
    ]
