# Generated by Django 3.1.4 on 2021-01-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_listhomework_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listhomework',
            name='notes',
        ),
    ]
