# Generated by Django 3.1.4 on 2021-01-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('notes', models.TextField(verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Заметки',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
